import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";

export const generateProfessionalPDF = async (analysis, analysisId) => {
  // A4 defaults to 595.28 x 841.89 points
  const doc = new jsPDF({ unit: "pt", format: "a4", orientation: "portrait" });
  
  const MARGIN_LEFT = 40;
  const PAGE_WIDTH = 595.28;
  const CONTENT_WIDTH = PAGE_WIDTH - 80;
  const PAGE_HEIGHT = 841.89;
  let cursorY = 40;
  let pageNum = 1;

  const COLOR_TEXT = "#111827"; // Dark gray almost black
  const COLOR_GRAY = "#6B7280";
  const COLOR_GREEN = "#059669";
  const COLOR_RED = "#DC2626";
  const COLOR_PRIMARY = "#4F46E5";

  function addFooter() {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(COLOR_GRAY);
    doc.text("Generated by ResumeAI", MARGIN_LEFT, PAGE_HEIGHT - 30);
    doc.text(`Page ${pageNum}`, PAGE_WIDTH - MARGIN_LEFT - 40, PAGE_HEIGHT - 30);
  }

  function checkPageBreak(neededHeight) {
    if (cursorY + neededHeight > PAGE_HEIGHT - 60) {
      addFooter();
      doc.addPage();
      pageNum++;
      cursorY = 50;
    }
  }

  // --- HEADER BLOCK ---
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(COLOR_PRIMARY);
  doc.text("ResumeAI ATS Report", MARGIN_LEFT, cursorY);
  cursorY += 30;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.setTextColor(COLOR_GRAY);
  const dateStr = new Date(analysis.created_at || Date.now()).toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric"
  });
  doc.text(`Generated on: ${dateStr}`, MARGIN_LEFT, cursorY);
  cursorY += 16;
  doc.text(`Target Role: ${analysis.job_title || "Not specified"}`, MARGIN_LEFT, cursorY);
  cursorY += 16;
  
  const score = analysis.ats_score || 0;
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLOR_TEXT);
  doc.text(`ATS Score: `, MARGIN_LEFT, cursorY);
  doc.setTextColor(score >= 70 ? COLOR_GREEN : COLOR_RED);
  doc.text(`${score.toFixed(1)} / 100`, MARGIN_LEFT + 70, cursorY);
  cursorY += 25;

  doc.setDrawColor(229, 231, 235);
  doc.line(MARGIN_LEFT, cursorY, PAGE_WIDTH - MARGIN_LEFT, cursorY);
  cursorY += 30;

  function addSectionTitle(title) {
    checkPageBreak(50);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(COLOR_TEXT);
    doc.text(title, MARGIN_LEFT, cursorY);
    cursorY += 22;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
  }

  function addTextBlock(lines, indent = 0) {
    for (const line of lines) {
      checkPageBreak(16);
      doc.text(line, MARGIN_LEFT + indent, cursorY);
      cursorY += 16;
    }
  }

  // --- SECTION 1: ATS Score Summary ---
  addSectionTitle("Section 1: ATS Score Summary");
  doc.setTextColor(COLOR_TEXT);
  const matchPct = analysis.match_percentage || 0;
  doc.text(`Job Description Match: ${matchPct.toFixed(1)}%`, MARGIN_LEFT, cursorY);
  cursorY += 25;

  // --- SECTION 2: Score Breakdown Table ---
  addSectionTitle("Section 2: Score Breakdown Table");
  const bd = analysis.ats_breakdown || {};
  doc.setTextColor(COLOR_TEXT);
  if (Object.keys(bd).length === 0) {
    addTextBlock(["No breakdown available."]);
  } else {
    for (const [key, val] of Object.entries(bd)) {
      const catScore = typeof val === "object" ? (val.score || 0) : val;
      checkPageBreak(20);
      doc.setFont("helvetica", "bold");
      doc.text(`${key.charAt(0).toUpperCase() + key.slice(1)}:`, MARGIN_LEFT, cursorY);
      doc.setFont("helvetica", "normal");
      doc.text(`${catScore.toFixed(1)} / 25 pts`, MARGIN_LEFT + 150, cursorY);
      cursorY += 16;
    }
  }
  cursorY += 20;

  // --- SECTION 3: Matched Keywords ---
  addSectionTitle("Section 3: Matched Keywords");
  const matched = (analysis.matched_keywords || []);
  if (matched.length > 0) {
    const wrapped = doc.splitTextToSize(matched.join(", "), CONTENT_WIDTH);
    doc.setTextColor(COLOR_GREEN);
    for (const line of wrapped) {
      checkPageBreak(16);
      doc.text(line, MARGIN_LEFT, cursorY);
      cursorY += 16;
    }
  } else {
    doc.setTextColor(COLOR_GRAY);
    addTextBlock(["No keywords matched."]);
  }
  cursorY += 20;

  // --- SECTION 4: Missing Keywords ---
  addSectionTitle("Section 4: Missing Keywords");
  const missing = (analysis.missing_keywords || []);
  if (missing.length > 0) {
    const wrapped2 = doc.splitTextToSize(missing.join(", "), CONTENT_WIDTH);
    doc.setTextColor(COLOR_RED);
    for (const line of wrapped2) {
      checkPageBreak(16);
      doc.text(line, MARGIN_LEFT, cursorY);
      cursorY += 16;
    }
  } else {
    doc.setTextColor(COLOR_GRAY);
    addTextBlock(["No critical keywords missing."]);
  }
  cursorY += 20;

  // --- SECTION 5: Skill Coverage Chart ---
  addSectionTitle("Section 5: Skill Coverage Chart");
  doc.setTextColor(COLOR_TEXT);
  
  const captureContainer = document.querySelector("#pdf-chart-capture-container");
  if (captureContainer && captureContainer.offsetHeight > 0) {
    checkPageBreak(300);
    try {
      const canvas = await html2canvas(captureContainer, {
        scale: 2,
        backgroundColor: "#ffffff",
        logging: false
      });
      const imgData = canvas.toDataURL("image/png");
      const ratio = canvas.height / canvas.width;
      const printWidth = Math.min(CONTENT_WIDTH, 500);
      const printHeight = printWidth * ratio;
      
      doc.addImage(imgData, "PNG", MARGIN_LEFT, cursorY, printWidth, printHeight);
      cursorY += printHeight + 20;
    } catch (err) {
      console.error("Chart export failed:", err);
      doc.setTextColor(COLOR_GRAY);
      addTextBlock(["Charts failed to render."]);
    }
  } else {
    doc.setTextColor(COLOR_GRAY);
    addTextBlock(["Charts not available for this analysis."]);
  }
  cursorY += 20;

  // --- SECTION 6: AI Suggestions ---
  addSectionTitle("Section 6: AI Suggestions");
  doc.setTextColor(COLOR_TEXT);
  let hasSuggestions = false;
  
  const ai = analysis.ai_suggestions || {};
  for (const [section, sugs] of Object.entries(ai)) {
    if (section.startsWith("_") || !Array.isArray(sugs) || sugs.length === 0) continue;
    hasSuggestions = true;
    checkPageBreak(30);
    doc.setFont("helvetica", "bold");
    doc.text(section.charAt(0).toUpperCase() + section.slice(1), MARGIN_LEFT, cursorY);
    cursorY += 18;
    doc.setFont("helvetica", "normal");
    
    for (const msg of sugs) {
      if (typeof msg === "object" && msg !== null) {
        if (msg.original && msg.improved) {
          checkPageBreak(35);
          doc.setFont("helvetica", "bold");
          doc.text("Original:", MARGIN_LEFT + 15, cursorY);
          cursorY += 16;
          doc.setFont("helvetica", "normal");
          
          let wrappedOrig = doc.splitTextToSize(msg.original, CONTENT_WIDTH - 20);
          for (let line of wrappedOrig) {
            checkPageBreak(16);
            doc.text(line, MARGIN_LEFT + 15, cursorY);
            cursorY += 16;
          }
          
          cursorY += 8;
          checkPageBreak(35);
          doc.setFont("helvetica", "bold");
          doc.text("Improved:", MARGIN_LEFT + 15, cursorY);
          cursorY += 16;
          doc.setFont("helvetica", "normal");
          
          let wrappedImp = doc.splitTextToSize(msg.improved, CONTENT_WIDTH - 20);
          for (let line of wrappedImp) {
            checkPageBreak(16);
            doc.text(line, MARGIN_LEFT + 15, cursorY);
            cursorY += 16;
          }
          cursorY += 16;
        } else {
          const textStr = Object.entries(msg).map(([k,v]) => `${k}: ${v}`).join(", ");
          const wrapped = doc.splitTextToSize(`• ${textStr}`, CONTENT_WIDTH - 15);
          for (const line of wrapped) {
             checkPageBreak(16);
             doc.text(line, MARGIN_LEFT + 15, cursorY);
             cursorY += 16;
          }
          cursorY += 6;
        }
      } else {
        const wrapped = doc.splitTextToSize(`• ${msg}`, CONTENT_WIDTH - 15);
        for (const line of wrapped) {
          checkPageBreak(16);
          doc.text(line, MARGIN_LEFT + 15, cursorY);
          cursorY += 16;
        }
        cursorY += 6;
      }
    }
    cursorY += 8;
  }
  
  if (analysis.grammar_issues?.length > 0) {
    hasSuggestions = true;
    checkPageBreak(30);
    doc.setFont("helvetica", "bold");
    doc.text("Grammar & Style", MARGIN_LEFT, cursorY);
    cursorY += 18;
    doc.setFont("helvetica", "normal");
    
    for (const issue of analysis.grammar_issues.slice(0, 15)) {
      const rep = issue.replacements?.[0] ? ` -> Suggestion: "${issue.replacements[0]}"` : "";
      const wrapped = doc.splitTextToSize(`• ${issue.message}${rep}`, CONTENT_WIDTH - 15);
      for (const line of wrapped) {
        checkPageBreak(16);
        doc.text(line, MARGIN_LEFT + 15, cursorY);
        cursorY += 16;
      }
      cursorY += 6;
    }
  }

  if (!hasSuggestions) {
    doc.setTextColor(COLOR_GRAY);
    addTextBlock(["No specific AI suggestions provided."]);
  }

  // Footer for last page
  addFooter();
  
  doc.save(`resume_analysis_report_${analysisId}.pdf`);
};
