"""add analysis limit tracking

Revision ID: 2fbf34b30062
Revises: 5b61fd63f3d4
Create Date: 2026-04-30 18:29:22.771480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fbf34b30062'
down_revision = '5b61fd63f3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('analysis_count')

    # ### end Alembic commands ###
