"""Add user subscription fields (nullable)

Revision ID: 5b61fd63f3d4
Revises: 73378e702556
Create Date: 2026-04-28 18:31:22.403980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b61fd63f3d4'
down_revision = '73378e702556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('subscription_expiry', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_expiry')
        batch_op.drop_column('subscription_active')

    # ### end Alembic commands ###
